create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_salt text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  company text,
  product_name text,
  source text not null default 'sales',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contact_submissions_status_idx on public.contact_submissions (status);
create index if not exists contact_submissions_created_at_idx on public.contact_submissions (created_at desc);
create index if not exists site_content_slug_idx on public.site_content (slug);

create table if not exists public.chatbot_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  role text not null check (role in ('user', 'assistant')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists chatbot_messages_session_id_idx on public.chatbot_messages (session_id);
create index if not exists chatbot_messages_created_at_idx on public.chatbot_messages (created_at desc);
