const normalizeRows = (payload) => {
  if (!payload) return [];
  if (Array.isArray(payload.rows)) return payload.rows;
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.data)) return payload.data;
  if (Array.isArray(payload.result)) return payload.result;
  return [];
};

const getNeonHttpConfig = () => {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) return null;
  const parsed = new URL(databaseUrl);
  return {
    sqlEndpoint: `https://${parsed.host}/sql`,
    databaseUrl
  };
};

export const isMissingTableError = (message = '') => /relation .* does not exist|Could not find the table/i.test(String(message));

// Observability: counts every round-trip to Neon. Set DB_QUERY_LOG=1 to log
// each query — used to verify the Redis cache is actually absorbing reads.
let dbQueryCount = 0;
export const getDbQueryCount = () => dbQueryCount;

const executeRawQuery = async (config, query, params = []) => {
  dbQueryCount += 1;
  if (process.env.DB_QUERY_LOG === '1') {
    console.log(`[db #${dbQueryCount}]`, query.slice(0, 90).replace(/\s+/g, ' '));
  }
  const response = await fetch(config.sqlEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Neon-Connection-String': config.databaseUrl
    },
    body: JSON.stringify({ query, params })
  });

  const text = await response.text();
  let payload = {};
  try {
    payload = text ? JSON.parse(text) : {};
  } catch {
    payload = { error: text };
  }

  if (!response.ok || payload.error) {
    throw new Error(payload.error?.message || payload.error || `Neon SQL request failed (${response.status})`);
  }

  return normalizeRows(payload);
};

const SCHEMA_QUERIES = [
  `create table if not exists public.admin_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_salt text not null,
    password_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.site_content (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    data jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.contact_submissions (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    subject text not null,
    message text not null,
    company text,
    product_name text,
    source text not null default 'sales',
    status text not null default 'new',
    consent_accepted boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `alter table public.contact_submissions add column if not exists consent_accepted boolean not null default false`,
  `create table if not exists public.chatbot_messages (
    id bigint generated by default as identity primary key,
    session_id text not null,
    conversation_id text,
    role text not null check (role in ('user', 'assistant')),
    message text not null,
    ip_address text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists contact_submissions_status_idx on public.contact_submissions (status)`,
  `create index if not exists contact_submissions_created_at_idx on public.contact_submissions (created_at desc)`,
  `create index if not exists site_content_slug_idx on public.site_content (slug)`,
  `create index if not exists chatbot_messages_session_id_idx on public.chatbot_messages (session_id)`,
  `create index if not exists chatbot_messages_conversation_id_idx on public.chatbot_messages (conversation_id)`,
  `create index if not exists chatbot_messages_created_at_idx on public.chatbot_messages (created_at desc)`,
  `create table if not exists public.page_views (
    id bigint generated by default as identity primary key,
    page text not null,
    referrer text,
    device_type text,
    browser text,
    session_id text,
    ip_hash text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists page_views_created_at_idx on public.page_views (created_at desc)`,
  `create index if not exists page_views_page_idx on public.page_views (page)`,
  `create index if not exists page_views_session_id_idx on public.page_views (session_id)`,
  `create table if not exists public.support_chats (
    id bigint generated by default as identity primary key,
    conversation_id text not null,
    customer_email text,
    sender text not null check (sender in ('customer', 'executive', 'system')),
    message text not null,
    executive_name text,
    created_at timestamptz not null default now()
  )`,
  `alter table public.support_chats drop constraint if exists support_chats_sender_check`,
  `alter table public.support_chats add constraint support_chats_sender_check check (sender in ('customer', 'executive', 'system'))`,
  `create index if not exists support_chats_conversation_id_idx on public.support_chats (conversation_id)`,
  `create index if not exists support_chats_created_at_idx on public.support_chats (created_at desc)`,
  `create table if not exists public.support_sessions (
    id bigint generated by default as identity primary key,
    conversation_id text not null unique,
    customer_email text,
    customer_name text,
    status text not null default 'waiting' check (status in ('waiting', 'active', 'closed')),
    assigned_executive text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists support_sessions_status_idx on public.support_sessions (status)`,
  `create index if not exists support_sessions_created_at_idx on public.support_sessions (created_at desc)`,
  `create table if not exists public.support_executives (
    id bigint generated by default as identity primary key,
    email text not null unique,
    name text not null,
    password_salt text not null,
    password_hash text not null,
    status text not null default 'invited' check (status in ('invited', 'active', 'inactive')),
    invite_token text,
    invite_expires_at timestamptz,
    last_seen_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists support_executives_email_idx on public.support_executives (email)`,
  `create index if not exists support_executives_status_idx on public.support_executives (status)`,
  `create index if not exists support_executives_invite_token_idx on public.support_executives (invite_token)`,
  `create table if not exists public.voice_rooms (
    id bigint generated by default as identity primary key,
    room_id text not null unique,
    conversation_id text not null,
    offer jsonb,
    answer jsonb,
    caller_candidates jsonb not null default '[]',
    callee_candidates jsonb not null default '[]',
    initiator text not null default 'customer' check (initiator in ('customer', 'executive')),
    status text not null default 'calling' check (status in ('calling', 'active', 'ended')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `alter table public.support_sessions add column if not exists customer_name text`,
  `alter table public.voice_rooms add column if not exists initiator text not null default 'customer'`,
  `create index if not exists voice_rooms_room_id_idx on public.voice_rooms (room_id)`,
  `create index if not exists voice_rooms_conversation_id_idx on public.voice_rooms (conversation_id)`,
  `alter table public.support_executives add column if not exists online_status text not null default 'offline' check (online_status in ('online', 'away', 'offline'))`,
  `create table if not exists public.executive_activity_logs (
    id bigint generated by default as identity primary key,
    executive_id bigint not null references public.support_executives(id) on delete cascade,
    action text not null check (action in ('login', 'logout', 'status_change', 'chat_assigned', 'chat_closed', 'call_started', 'call_ended')),
    old_status text,
    new_status text,
    metadata jsonb,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists executive_activity_logs_executive_id_idx on public.executive_activity_logs (executive_id)`,
  `create index if not exists executive_activity_logs_created_at_idx on public.executive_activity_logs (created_at desc)`,
  // Internal 1:1 chat between support executives
  `create table if not exists public.executive_internal_messages (
    id bigint generated by default as identity primary key,
    from_id bigint not null references public.support_executives(id) on delete cascade,
    from_name text not null,
    to_id bigint not null references public.support_executives(id) on delete cascade,
    message text not null,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists executive_internal_messages_pair_idx on public.executive_internal_messages (from_id, to_id, created_at desc)`,
  `create index if not exists executive_internal_messages_to_idx on public.executive_internal_messages (to_id, created_at desc)`,
  // Conversation / call handoff requests between executives (kept as the admin audit log)
  `create table if not exists public.chat_transfers (
    id bigint generated by default as identity primary key,
    conversation_id text not null,
    from_id bigint references public.support_executives(id) on delete set null,
    from_name text not null,
    to_id bigint not null references public.support_executives(id) on delete cascade,
    to_name text not null,
    kind text not null default 'chat' check (kind in ('chat', 'call')),
    status text not null default 'pending' check (status in ('pending', 'accepted', 'denied', 'cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists chat_transfers_to_status_idx on public.chat_transfers (to_id, status)`,
  `create index if not exists chat_transfers_conversation_idx on public.chat_transfers (conversation_id, created_at desc)`,
  // Internal team members (ticket portal accounts) — invited by admin, @patienceai.in only
  `create table if not exists public.team_members (
    id bigint generated by default as identity primary key,
    email text not null unique,
    name text not null,
    password_salt text not null,
    password_hash text not null,
    status text not null default 'invited' check (status in ('invited', 'active', 'inactive')),
    invite_token text,
    invite_expires_at timestamptz,
    last_seen_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists team_members_email_idx on public.team_members (email)`,
  `create index if not exists team_members_invite_token_idx on public.team_members (invite_token)`,
  // Support tickets — raised by executives, assigned to internal team members
  `create table if not exists public.support_tickets (
    id bigint generated by default as identity primary key,
    subject text not null,
    description text,
    priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
    status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
    conversation_id text,
    customer_email text,
    customer_name text,
    created_by_id bigint,
    created_by_name text,
    assignee_email text not null,
    assignee_name text,
    client_email_status text not null default 'pending',
    assignee_email_status text not null default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists support_tickets_assignee_idx on public.support_tickets (assignee_email, created_at desc)`,
  `create index if not exists support_tickets_status_idx on public.support_tickets (status)`,
  `create index if not exists support_tickets_conversation_idx on public.support_tickets (conversation_id)`,
  // Ticket comments — Jira-style thread / chat between executive and assignee
  `create table if not exists public.ticket_comments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references public.support_tickets(id) on delete cascade,
    author_role text not null check (author_role in ('executive', 'member', 'admin', 'system')),
    author_name text,
    author_email text,
    message text not null,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists ticket_comments_ticket_idx on public.ticket_comments (ticket_id, created_at asc)`,
  // v2: categories, SLA, escalation, attachments, notifications, audit, KB
  `alter table public.support_tickets add column if not exists category text not null default 'General Inquiry'`,
  `alter table public.support_tickets add column if not exists due_at timestamptz`,
  `alter table public.support_tickets add column if not exists first_response_at timestamptz`,
  `alter table public.support_tickets add column if not exists resolved_at timestamptz`,
  `alter table public.support_tickets add column if not exists escalation_level int not null default 0`,
  `alter table public.support_tickets add column if not exists last_reminder_at timestamptz`,
  `alter table public.support_tickets add column if not exists sla_warned boolean not null default false`,
  `alter table public.support_tickets add column if not exists sla_breached boolean not null default false`,
  `alter table public.support_tickets add column if not exists closed_by_client boolean not null default false`,
  `alter table public.ticket_comments add column if not exists is_internal boolean not null default false`,
  `alter table public.ticket_comments drop constraint if exists ticket_comments_author_role_check`,
  `alter table public.ticket_comments add constraint ticket_comments_author_role_check check (author_role in ('executive', 'member', 'admin', 'system', 'client'))`,
  `create table if not exists public.ticket_categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now()
  )`,
  `create table if not exists public.sla_policies (
    id bigint generated by default as identity primary key,
    priority text not null unique check (priority in ('low', 'medium', 'high', 'urgent')),
    hours int not null,
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.ticket_attachments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references public.support_tickets(id) on delete cascade,
    comment_id bigint,
    file_name text not null,
    content_type text not null,
    size_bytes int not null,
    data_base64 text not null,
    uploaded_by_name text,
    uploaded_by_role text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists ticket_attachments_ticket_idx on public.ticket_attachments (ticket_id, created_at asc)`,
  // v3: attachments live in Cloudflare R2; base64-in-DB is only a fallback when R2 is unconfigured
  `alter table public.ticket_attachments alter column data_base64 drop not null`,
  `alter table public.ticket_attachments add column if not exists storage text not null default 'db'`,
  `alter table public.ticket_attachments add column if not exists r2_key text`,
  `create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    recipient_email text not null,
    type text not null,
    ticket_id bigint,
    message text not null,
    read boolean not null default false,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists notifications_recipient_idx on public.notifications (recipient_email, read, created_at desc)`,
  `create table if not exists public.ticket_escalations (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references public.support_tickets(id) on delete cascade,
    level int not null,
    reason text,
    notified_email text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists ticket_escalations_ticket_idx on public.ticket_escalations (ticket_id, created_at desc)`,
  `create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_role text,
    actor_email text,
    action text not null,
    target text,
    metadata jsonb,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc)`,
  `create table if not exists public.kb_articles (
    id bigint generated by default as identity primary key,
    title text not null,
    kind text not null default 'article' check (kind in ('article', 'faq', 'guide')),
    body text not null,
    tags text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  // PEOS — engineering operating system (extends tickets; nothing removed)
  `alter table public.support_tickets add column if not exists ticket_type text not null default 'support'`,
  `alter table public.support_tickets add column if not exists epic_id bigint`,
  `alter table public.support_tickets add column if not exists sprint_id bigint`,
  `alter table public.support_tickets add column if not exists story_points int`,
  `create table if not exists public.epics (
    id bigint generated by default as identity primary key,
    title text not null, description text, status text not null default 'open',
    owner_email text, milestone text, created_at timestamptz not null default now()
  )`,
  `create table if not exists public.sprints (
    id bigint generated by default as identity primary key,
    name text not null, goal text, status text not null default 'planned',
    starts_on date, ends_on date, capacity_points int, created_at timestamptz not null default now()
  )`,
  `create table if not exists public.incidents (
    id bigint generated by default as identity primary key,
    title text not null, severity text not null default 'SEV-3' check (severity in ('SEV-1','SEV-2','SEV-3','SEV-4')),
    status text not null default 'investigating' check (status in ('investigating','resolved','postmortem','closed')),
    service text, owner_email text, summary text, postmortem text,
    ticket_id bigint, created_at timestamptz not null default now(), resolved_at timestamptz
  )`,
  `create table if not exists public.services_catalog (
    id bigint generated by default as identity primary key,
    name text not null unique, description text, owner_email text, backup_owner_email text,
    team text, repository text, runbook text, sla text, dependencies text,
    api_docs text, created_at timestamptz not null default now()
  )`,
  `create table if not exists public.okrs (
    id bigint generated by default as identity primary key,
    level text not null default 'company' check (level in ('company','department','team','sprint')),
    objective text not null, key_result text, progress int not null default 0,
    owner_email text, parent_id bigint, quarter text, created_at timestamptz not null default now()
  )`,
  `create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    kind text not null default 'company', title text not null, body text,
    author text, created_at timestamptz not null default now()
  )`,
  `create table if not exists public.ticket_github_links (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null, kind text not null check (kind in ('branch','commit','pr','release')),
    ref text not null, title text, url text, author text, state text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists ticket_github_links_ticket_idx on public.ticket_github_links (ticket_id)`,
  // QA module — test cases with embedded latest run result
  `create table if not exists public.qa_test_cases (
    id bigint generated by default as identity primary key,
    ticket_id bigint, title text not null, steps text, expected text,
    last_result text not null default 'pending' check (last_result in ('pending','pass','fail','blocked')),
    run_notes text, run_by text, run_at timestamptz,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists qa_test_cases_ticket_idx on public.qa_test_cases (ticket_id)`,
  `create table if not exists public.saved_responses (
    id bigint generated by default as identity primary key,
    label text not null,
    body text not null,
    kind text not null default 'general',
    created_at timestamptz not null default now()
  )`
];

let schemaReady = false;
let schemaPromise = null;

const ensureSchema = async (config) => {
  if (schemaReady) return;
  if (!schemaPromise) {
    schemaPromise = (async () => {
      for (const schemaQuery of SCHEMA_QUERIES) {
        await executeRawQuery(config, schemaQuery);
      }
      schemaReady = true;
    })().catch((error) => {
      schemaPromise = null;
      throw error;
    });
  }
  await schemaPromise;
};

export const queryDb = async (query, params = []) => {
  const config = getNeonHttpConfig();
  if (!config) {
    throw new Error('NeonDB is not configured. Set DATABASE_URL.');
  }
  await ensureSchema(config);
  return executeRawQuery(config, query, params);
};
