const normalizeRows = (payload) => {
  if (!payload) return [];
  if (Array.isArray(payload.rows)) return payload.rows;
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.data)) return payload.data;
  if (Array.isArray(payload.result)) return payload.result;
  return [];
};

const getNeonHttpConfig = () => {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) return null;
  const parsed = new URL(databaseUrl);
  return {
    sqlEndpoint: `https://${parsed.host}/sql`,
    databaseUrl
  };
};

export const isMissingTableError = (message = '') => /relation .* does not exist|Could not find the table/i.test(String(message));

const executeRawQuery = async (config, query, params = []) => {
  const response = await fetch(config.sqlEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Neon-Connection-String': config.databaseUrl
    },
    body: JSON.stringify({ query, params })
  });

  const text = await response.text();
  let payload = {};
  try {
    payload = text ? JSON.parse(text) : {};
  } catch {
    payload = { error: text };
  }

  if (!response.ok || payload.error) {
    throw new Error(payload.error?.message || payload.error || `Neon SQL request failed (${response.status})`);
  }

  return normalizeRows(payload);
};

const SCHEMA_QUERIES = [
  `create table if not exists public.admin_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_salt text not null,
    password_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.site_content (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    data jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.contact_submissions (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    subject text not null,
    message text not null,
    company text,
    product_name text,
    source text not null default 'sales',
    status text not null default 'new',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists public.chatbot_messages (
    id bigint generated by default as identity primary key,
    session_id text not null,
    conversation_id text,
    role text not null check (role in ('user', 'assistant')),
    message text not null,
    ip_address text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists contact_submissions_status_idx on public.contact_submissions (status)`,
  `create index if not exists contact_submissions_created_at_idx on public.contact_submissions (created_at desc)`,
  `create index if not exists site_content_slug_idx on public.site_content (slug)`,
  `create index if not exists chatbot_messages_session_id_idx on public.chatbot_messages (session_id)`,
  `create index if not exists chatbot_messages_conversation_id_idx on public.chatbot_messages (conversation_id)`,
  `create index if not exists chatbot_messages_created_at_idx on public.chatbot_messages (created_at desc)`,
  `create table if not exists public.page_views (
    id bigint generated by default as identity primary key,
    page text not null,
    referrer text,
    device_type text,
    browser text,
    session_id text,
    ip_hash text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists page_views_created_at_idx on public.page_views (created_at desc)`,
  `create index if not exists page_views_page_idx on public.page_views (page)`,
  `create index if not exists page_views_session_id_idx on public.page_views (session_id)`,
  `create table if not exists public.support_executives (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_salt text,
    password_hash text,
    invite_token_hash text,
    invite_sent_at timestamptz,
    invite_accepted_at timestamptz,
    status text not null default 'invited' check (status in ('invited', 'accepted', 'active', 'disabled')),
    display_name text,
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists support_executives_status_idx on public.support_executives (status)`,
  `create table if not exists public.support_chat_conversations (
    id bigint generated by default as identity primary key,
    conversation_id text not null unique,
    customer_name text,
    customer_email text,
    executive_email text,
    assigned_at timestamptz,
    status text not null default 'waiting' check (status in ('waiting', 'active', 'closed')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
  `create index if not exists support_chat_conversations_status_idx on public.support_chat_conversations (status)`,
  `create table if not exists public.support_chat_messages (
    id bigint generated by default as identity primary key,
    conversation_id text not null,
    sender_role text not null check (sender_role in ('customer', 'executive', 'admin', 'system')),
    sender_email text,
    message_type text not null default 'text' check (message_type in ('text', 'file', 'typing', 'system')),
    message text not null,
    attachment_name text,
    attachment_url text,
    attachment_size bigint,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists support_chat_messages_conversation_idx on public.support_chat_messages (conversation_id, created_at desc)`
  ,
  `create table if not exists public.auth_login_events (
    id bigint generated by default as identity primary key,
    role text not null check (role in ('admin', 'support')),
    identifier text not null,
    status text not null check (status in ('success', 'failure')),
    ip_address text,
    user_agent text,
    created_at timestamptz not null default now()
  )`,
  `create index if not exists auth_login_events_role_created_idx on public.auth_login_events (role, created_at desc)`
];

let schemaReady = false;
let schemaPromise = null;

const ensureSchema = async (config) => {
  if (schemaReady) return;
  if (!schemaPromise) {
    schemaPromise = (async () => {
      for (const schemaQuery of SCHEMA_QUERIES) {
        await executeRawQuery(config, schemaQuery);
      }
      schemaReady = true;
    })().catch((error) => {
      schemaPromise = null;
      throw error;
    });
  }
  await schemaPromise;
};

export const queryDb = async (query, params = []) => {
  const config = getNeonHttpConfig();
  if (!config) {
    throw new Error('NeonDB is not configured. Set DATABASE_URL.');
  }
  await ensureSchema(config);
  return executeRawQuery(config, query, params);
};
