// ─────────────────────────────────────────────────────────────────────────────
// Business Growth OS — the AI-powered replacement for the legacy Marketing
// Automation module. One unified, Node-native surface (no Python backend) that
// powers the /growth portal: CRM, sales pipeline, marketing campaigns, activity
// timeline, tasks, an executive command-center metrics roll-up, revenue
// forecasting, a business health score and a data-grounded AI copilot.
//
// Persistence reuses the app's Neon layer (queryDb). Auth reuses the existing
// team-member / support-exec session — any signed-in operator gets access.
// ─────────────────────────────────────────────────────────────────────────────
import { queryDb, isMissingTableError } from './_db.js';
import { getMemberSession, getExecSession } from './_security.js';
import { aiComplete } from './_ai.js';
import { sendEmail } from './_email.js';
import { logAudit } from './_ticketing.js';

// Department-specific welcome blurb for the onboarding email HR triggers on hire.
const DEPT_WELCOME = {
  Engineering: 'Your manager will set you up with repo access, the dev environment and your first onboarding tickets.',
  Sales: 'You\'ll get CRM access, your territory/accounts and a ramp plan with quota expectations.',
  Marketing: 'You\'ll join the campaigns calendar, brand assets and analytics dashboards.',
  'Customer Success': 'You\'ll be assigned your first accounts and the health-monitoring playbooks.',
  Finance: 'You\'ll receive access to invoicing, expenses and the reporting suite.',
  HR: 'You\'ll get the HRIS, policies and the people-ops handbook.',
  Operations: 'You\'ll be added to the ops runbooks and tooling.',
  Product: 'You\'ll get the roadmap, design files and the discovery backlog.',
};

const sendOnboardingEmail = async (emp) => {
  if (!emp?.email) return;
  const blurb = DEPT_WELCOME[emp.department] || 'Your manager will share your onboarding plan shortly.';
  await sendEmail({
    to: { email: emp.email, name: emp.name },
    subject: `Welcome to Patience AI, ${emp.name}! 🎉`,
    html: `<div style="font-family:sans-serif;max-width:520px;margin:auto;padding:32px">
      <h2 style="color:#0f172a">Welcome aboard, ${emp.name}!</h2>
      <p style="color:#475569">We're thrilled to have you join the <strong>${emp.department}</strong> team${emp.title ? ` as <strong>${emp.title}</strong>` : ''}.</p>
      <p style="color:#475569">${blurb}</p>
      <p style="color:#475569">${emp.start_date ? `Your start date is <strong>${emp.start_date}</strong>. ` : ''}${emp.manager_email ? `Your manager (${emp.manager_email}) will be in touch with next steps.` : ''}</p>
      <p style="color:#94a3b8;font-size:12px">Sent automatically by the Patience AI People team.</p>
    </div>`,
    text: `Welcome aboard, ${emp.name}!\n\nWe're thrilled to have you join the ${emp.department} team${emp.title ? ` as ${emp.title}` : ''}.\n\n${blurb}\n\n${emp.start_date ? `Start date: ${emp.start_date}. ` : ''}${emp.manager_email ? `Your manager (${emp.manager_email}) will be in touch.` : ''}`,
  }).catch((e) => console.error('[onboarding email] failed:', e.message));
};

const actorOf = (req) => getMemberSession(req) || getExecSession(req);

// Whitelisted enums keep the UI and DB honest and make analytics predictable.
const CONTACT_TYPES = ['lead', 'prospect', 'customer', 'partner', 'vendor'];
const CONTACT_STAGES = ['new', 'engaged', 'qualified', 'active', 'at_risk', 'churned'];
const DEAL_STAGES = ['discovery', 'qualified', 'proposal', 'negotiation', 'won', 'lost'];
const DEAL_OPEN_STAGES = ['discovery', 'qualified', 'proposal', 'negotiation'];
const CAMPAIGN_CHANNELS = ['email', 'social', 'paid_ads', 'content', 'events', 'referral', 'webinar'];
const CAMPAIGN_STATUSES = ['draft', 'scheduled', 'active', 'paused', 'completed'];
const TASK_STATUSES = ['open', 'in_progress', 'done'];
// Accounts (finance) + HR enums.
const INVOICE_STATUSES = ['draft', 'sent', 'paid', 'overdue', 'void'];
const EXPENSE_STATUSES = ['pending', 'approved', 'paid', 'rejected'];
const EXPENSE_CATEGORIES = ['marketing', 'salaries', 'software', 'travel', 'office', 'infra', 'other'];
const DEPARTMENTS = ['Engineering', 'Sales', 'Marketing', 'Customer Success', 'Finance', 'HR', 'Operations', 'Product'];
const EMP_STATUSES = ['active', 'on_leave', 'probation', 'offboarding', 'terminated'];
const EMP_TYPES = ['full_time', 'part_time', 'contract', 'intern'];
const EMP_CATEGORIES = ['team', 'support', 'hr', 'other'];
const oneOf = (v, list, fallback) => (list.includes(v) ? v : fallback);
const num = (v, d = 0) => { const n = Number(v); return Number.isFinite(n) ? n : d; };
const clip = (v, n) => (v == null ? null : String(v).slice(0, n));

// ── Schema (lazy, idempotent) ───────────────────────────────────────────────
let ready = false;
const ensure = async () => {
  if (ready) return;
  await queryDb(`create table if not exists public.business_contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text,
    company text,
    phone text,
    type text not null default 'lead',
    stage text not null default 'new',
    owner_email text,
    value numeric not null default 0,
    health int not null default 70,
    score int not null default 0,
    tags text,
    notes text,
    last_touch timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  await queryDb(`create table if not exists public.business_deals (
    id bigint generated by default as identity primary key,
    title text not null,
    contact_id bigint,
    pipeline text not null default 'sales',
    stage text not null default 'discovery',
    value numeric not null default 0,
    currency text not null default 'INR',
    probability int not null default 20,
    owner_email text,
    status text not null default 'open',
    close_date date,
    lost_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  await queryDb(`create table if not exists public.business_campaigns (
    id bigint generated by default as identity primary key,
    name text not null,
    channel text not null default 'email',
    status text not null default 'draft',
    budget numeric not null default 0,
    spend numeric not null default 0,
    leads int not null default 0,
    conversions int not null default 0,
    revenue numeric not null default 0,
    start_date date,
    end_date date,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  await queryDb(`create table if not exists public.business_activities (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    type text not null default 'note',
    subject text,
    body text,
    actor_email text,
    created_at timestamptz not null default now()
  )`);
  await queryDb(`create table if not exists public.business_tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    due_date date,
    assignee_email text,
    status text not null default 'open',
    contact_id bigint,
    deal_id bigint,
    created_at timestamptz not null default now()
  )`);
  // Accounts — receivables (invoices) and payables (expenses).
  await queryDb(`create table if not exists public.business_invoices (
    id bigint generated by default as identity primary key,
    number text,
    client_name text not null,
    contact_id bigint,
    amount numeric not null default 0,
    tax numeric not null default 0,
    status text not null default 'draft',
    issue_date date,
    due_date date,
    paid_date date,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  await queryDb(`create table if not exists public.business_expenses (
    id bigint generated by default as identity primary key,
    vendor text not null,
    category text not null default 'other',
    amount numeric not null default 0,
    status text not null default 'pending',
    spend_date date,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  // HR — employee directory.
  await queryDb(`create table if not exists public.business_employees (
    id bigint generated by default as identity primary key,
    name text not null,
    email text,
    title text,
    department text not null default 'Operations',
    status text not null default 'active',
    employment_type text not null default 'full_time',
    salary numeric not null default 0,
    location text,
    manager_email text,
    start_date date,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`);
  await queryDb(`alter table public.business_employees add column if not exists category text not null default 'other'`);
  // HR — leave records for the worklog view.
  await queryDb(`create table if not exists public.business_leaves (
    id bigint generated by default as identity primary key,
    employee_id bigint,
    employee_email text,
    type text not null default 'casual',
    start_date date,
    end_date date,
    days numeric not null default 1,
    status text not null default 'approved',
    reason text,
    created_at timestamptz not null default now()
  )`);
  await queryDb(`create index if not exists business_leaves_emp_idx on public.business_leaves (employee_id)`);
  ready = true;
};

const touchContact = (id) =>
  queryDb(`update business_contacts set last_touch=now(), updated_at=now() where id=$1`, [id]).catch(() => {});

// ── CRUD resources ───────────────────────────────────────────────────────────
async function contacts(method, req, me) {
  if (method === 'GET') {
    const rows = await queryDb(`select * from business_contacts order by updated_at desc limit 500`);
    return { contacts: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_contacts (name,email,company,phone,type,stage,owner_email,value,health,score,tags,notes,last_touch)
       values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()) returning *`,
      [clip(b.name, 160) || 'Unnamed', clip(b.email, 200), clip(b.company, 160), clip(b.phone, 40),
       oneOf(b.type, CONTACT_TYPES, 'lead'), oneOf(b.stage, CONTACT_STAGES, 'new'), me.email,
       num(b.value), Math.max(0, Math.min(100, num(b.health, 70))), Math.max(0, Math.min(100, num(b.score))),
       clip(b.tags, 300), clip(b.notes, 4000)]
    );
    return { contact: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const rows = await queryDb(
      `update business_contacts set
        name=coalesce($2,name), email=coalesce($3,email), company=coalesce($4,company), phone=coalesce($5,phone),
        type=coalesce($6,type), stage=coalesce($7,stage), value=coalesce($8,value),
        health=coalesce($9,health), score=coalesce($10,score), tags=coalesce($11,tags), notes=coalesce($12,notes),
        updated_at=now()
       where id=$1 returning *`,
      [b.id, clip(b.name, 160), clip(b.email, 200), clip(b.company, 160), clip(b.phone, 40),
       b.type ? oneOf(b.type, CONTACT_TYPES, 'lead') : null, b.stage ? oneOf(b.stage, CONTACT_STAGES, 'new') : null,
       b.value != null ? num(b.value) : null, b.health != null ? Math.max(0, Math.min(100, num(b.health))) : null,
       b.score != null ? Math.max(0, Math.min(100, num(b.score))) : null, b.tags != null ? clip(b.tags, 300) : null,
       b.notes != null ? clip(b.notes, 4000) : null]
    );
    return { contact: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_contacts where id=$1`, [id]);
    await queryDb(`delete from business_activities where contact_id=$1`, [id]).catch(() => {});
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

async function deals(method, req, me) {
  if (method === 'GET') {
    const rows = await queryDb(
      `select d.*, c.name as contact_name, c.company as contact_company
       from business_deals d left join business_contacts c on c.id=d.contact_id
       order by d.updated_at desc limit 500`
    );
    return { deals: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_deals (title,contact_id,pipeline,stage,value,currency,probability,owner_email,status,close_date)
       values ($1,$2,$3,$4,$5,$6,$7,$8,'open',$9) returning *`,
      [clip(b.title, 200) || 'New opportunity', b.contact_id || null, clip(b.pipeline, 60) || 'sales',
       oneOf(b.stage, DEAL_STAGES, 'discovery'), num(b.value), clip(b.currency, 8) || 'INR',
       Math.max(0, Math.min(100, num(b.probability, 20))), me.email, b.close_date || null]
    );
    if (b.contact_id) touchContact(b.contact_id);
    return { deal: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    // Moving to won/lost auto-sets status; probability snaps to 100/0.
    let status = b.status, probability = b.probability;
    if (b.stage === 'won') { status = 'won'; probability = 100; }
    if (b.stage === 'lost') { status = 'lost'; probability = 0; }
    const rows = await queryDb(
      `update business_deals set
        title=coalesce($2,title), stage=coalesce($3,stage), value=coalesce($4,value),
        probability=coalesce($5,probability), status=coalesce($6,status), close_date=coalesce($7,close_date),
        lost_reason=coalesce($8,lost_reason), contact_id=coalesce($9,contact_id), updated_at=now()
       where id=$1 returning *`,
      [b.id, clip(b.title, 200), b.stage ? oneOf(b.stage, DEAL_STAGES, 'discovery') : null,
       b.value != null ? num(b.value) : null, probability != null ? Math.max(0, Math.min(100, num(probability))) : null,
       status || null, b.close_date || null, clip(b.lost_reason, 300), b.contact_id || null]
    );
    return { deal: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_deals where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

async function campaigns(method, req) {
  if (method === 'GET') {
    const rows = await queryDb(`select * from business_campaigns order by updated_at desc limit 300`);
    return { campaigns: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_campaigns (name,channel,status,budget,spend,leads,conversions,revenue,start_date,end_date)
       values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,
      [clip(b.name, 160) || 'Untitled campaign', oneOf(b.channel, CAMPAIGN_CHANNELS, 'email'),
       oneOf(b.status, CAMPAIGN_STATUSES, 'draft'), num(b.budget), num(b.spend), num(b.leads),
       num(b.conversions), num(b.revenue), b.start_date || null, b.end_date || null]
    );
    return { campaign: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const rows = await queryDb(
      `update business_campaigns set
        name=coalesce($2,name), channel=coalesce($3,channel), status=coalesce($4,status),
        budget=coalesce($5,budget), spend=coalesce($6,spend), leads=coalesce($7,leads),
        conversions=coalesce($8,conversions), revenue=coalesce($9,revenue),
        start_date=coalesce($10,start_date), end_date=coalesce($11,end_date), updated_at=now()
       where id=$1 returning *`,
      [b.id, clip(b.name, 160), b.channel ? oneOf(b.channel, CAMPAIGN_CHANNELS, 'email') : null,
       b.status ? oneOf(b.status, CAMPAIGN_STATUSES, 'draft') : null,
       b.budget != null ? num(b.budget) : null, b.spend != null ? num(b.spend) : null,
       b.leads != null ? num(b.leads) : null, b.conversions != null ? num(b.conversions) : null,
       b.revenue != null ? num(b.revenue) : null, b.start_date || null, b.end_date || null]
    );
    return { campaign: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_campaigns where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

async function activities(method, req, me) {
  if (method === 'GET') {
    const cid = parseInt(req.query.contact_id, 10);
    const rows = cid
      ? await queryDb(`select * from business_activities where contact_id=$1 order by created_at desc limit 200`, [cid])
      : await queryDb(`select * from business_activities order by created_at desc limit 200`);
    return { activities: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_activities (contact_id,type,subject,body,actor_email)
       values ($1,$2,$3,$4,$5) returning *`,
      [b.contact_id || null, clip(b.type, 40) || 'note', clip(b.subject, 200), clip(b.body, 4000), me.email]
    );
    if (b.contact_id) touchContact(b.contact_id);
    return { activity: rows[0] };
  }
  throw httpErr(405, 'Method not allowed');
}

async function tasks(method, req, me) {
  if (method === 'GET') {
    const rows = await queryDb(`select * from business_tasks order by (status='done'), due_date nulls last, created_at desc limit 300`);
    return { tasks: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_tasks (title,due_date,assignee_email,status,contact_id,deal_id)
       values ($1,$2,$3,$4,$5,$6) returning *`,
      [clip(b.title, 200) || 'Follow up', b.due_date || null, clip(b.assignee_email, 200) || me.email,
       oneOf(b.status, TASK_STATUSES, 'open'), b.contact_id || null, b.deal_id || null]
    );
    return { task: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const rows = await queryDb(
      `update business_tasks set title=coalesce($2,title), due_date=coalesce($3,due_date),
        status=coalesce($4,status) where id=$1 returning *`,
      [b.id, clip(b.title, 200), b.due_date || null, b.status ? oneOf(b.status, TASK_STATUSES, 'open') : null]
    );
    return { task: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_tasks where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

// ── Accounts: invoices (AR) ───────────────────────────────────────────────────
async function invoices(method, req) {
  if (method === 'GET') {
    const rows = await queryDb(
      `select i.*, c.company as contact_company from business_invoices i
       left join business_contacts c on c.id=i.contact_id order by i.updated_at desc limit 500`
    );
    return { invoices: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_invoices (number,client_name,contact_id,amount,tax,status,issue_date,due_date,paid_date,notes)
       values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,
      [clip(b.number, 40) || `INV-${Date.now().toString().slice(-6)}`, clip(b.client_name, 160) || 'Client',
       b.contact_id || null, num(b.amount), num(b.tax), oneOf(b.status, INVOICE_STATUSES, 'draft'),
       b.issue_date || null, b.due_date || null, b.status === 'paid' ? (b.paid_date || new Date().toISOString().slice(0, 10)) : (b.paid_date || null), clip(b.notes, 2000)]
    );
    return { invoice: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const paid = b.status === 'paid' ? (b.paid_date || new Date().toISOString().slice(0, 10)) : (b.paid_date || null);
    const rows = await queryDb(
      `update business_invoices set number=coalesce($2,number), client_name=coalesce($3,client_name),
        contact_id=coalesce($4,contact_id), amount=coalesce($5,amount), tax=coalesce($6,tax),
        status=coalesce($7,status), issue_date=coalesce($8,issue_date), due_date=coalesce($9,due_date),
        paid_date=$10, notes=coalesce($11,notes), updated_at=now() where id=$1 returning *`,
      [b.id, clip(b.number, 40), clip(b.client_name, 160), b.contact_id || null,
       b.amount != null ? num(b.amount) : null, b.tax != null ? num(b.tax) : null,
       b.status ? oneOf(b.status, INVOICE_STATUSES, 'draft') : null, b.issue_date || null, b.due_date || null,
       paid, b.notes != null ? clip(b.notes, 2000) : null]
    );
    return { invoice: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_invoices where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

// ── Accounts: expenses (AP) ────────────────────────────────────────────────────
async function expenses(method, req) {
  if (method === 'GET') {
    const rows = await queryDb(`select * from business_expenses order by updated_at desc limit 500`);
    return { expenses: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_expenses (vendor,category,amount,status,spend_date,notes)
       values ($1,$2,$3,$4,$5,$6) returning *`,
      [clip(b.vendor, 160) || 'Vendor', oneOf(b.category, EXPENSE_CATEGORIES, 'other'), num(b.amount),
       oneOf(b.status, EXPENSE_STATUSES, 'pending'), b.spend_date || null, clip(b.notes, 2000)]
    );
    return { expense: rows[0] };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const rows = await queryDb(
      `update business_expenses set vendor=coalesce($2,vendor), category=coalesce($3,category),
        amount=coalesce($4,amount), status=coalesce($5,status), spend_date=coalesce($6,spend_date),
        notes=coalesce($7,notes), updated_at=now() where id=$1 returning *`,
      [b.id, clip(b.vendor, 160), b.category ? oneOf(b.category, EXPENSE_CATEGORIES, 'other') : null,
       b.amount != null ? num(b.amount) : null, b.status ? oneOf(b.status, EXPENSE_STATUSES, 'pending') : null,
       b.spend_date || null, b.notes != null ? clip(b.notes, 2000) : null]
    );
    return { expense: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_expenses where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

// ── HR: employee directory ──────────────────────────────────────────────────────
async function employees(method, req) {
  if (method === 'GET') {
    const rows = await queryDb(`select * from business_employees order by department asc, name asc limit 1000`);
    return { employees: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const rows = await queryDb(
      `insert into business_employees (name,email,title,department,status,employment_type,salary,location,manager_email,start_date,notes,category)
       values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *`,
      [clip(b.name, 160) || 'New hire', clip(b.email, 200), clip(b.title, 120),
       oneOf(b.department, DEPARTMENTS, 'Operations'), oneOf(b.status, EMP_STATUSES, 'active'),
       oneOf(b.employment_type, EMP_TYPES, 'full_time'), num(b.salary), clip(b.location, 120),
       clip(b.manager_email, 200), b.start_date || null, clip(b.notes, 2000), oneOf(b.category, EMP_CATEGORIES, 'other')]
    );
    // Trigger the onboarding welcome email (fire-and-forget) when HR adds a hire.
    if (b.sendOnboarding !== false) sendOnboardingEmail(rows[0]);
    return { employee: rows[0], onboardingEmailSent: Boolean(rows[0]?.email) };
  }
  if (method === 'PATCH') {
    if (!b.id) throw httpErr(400, 'id required');
    const rows = await queryDb(
      `update business_employees set name=coalesce($2,name), email=coalesce($3,email), title=coalesce($4,title),
        department=coalesce($5,department), status=coalesce($6,status), employment_type=coalesce($7,employment_type),
        salary=coalesce($8,salary), location=coalesce($9,location), manager_email=coalesce($10,manager_email),
        start_date=coalesce($11,start_date), notes=coalesce($12,notes), category=coalesce($13,category), updated_at=now() where id=$1 returning *`,
      [b.id, clip(b.name, 160), clip(b.email, 200), clip(b.title, 120),
       b.department ? oneOf(b.department, DEPARTMENTS, 'Operations') : null, b.status ? oneOf(b.status, EMP_STATUSES, 'active') : null,
       b.employment_type ? oneOf(b.employment_type, EMP_TYPES, 'full_time') : null, b.salary != null ? num(b.salary) : null,
       b.location != null ? clip(b.location, 120) : null, b.manager_email != null ? clip(b.manager_email, 200) : null,
       b.start_date || null, b.notes != null ? clip(b.notes, 2000) : null, b.category ? oneOf(b.category, EMP_CATEGORIES, 'other') : null]
    );
    return { employee: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_employees where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

// ── HR worklog: leave records + presence-derived work hours ───────────────────
const LEAVE_TYPES = ['casual', 'sick', 'earned', 'unpaid', 'wfh'];
const LEAVE_STATUSES = ['pending', 'approved', 'rejected'];

async function leaves(method, req) {
  if (method === 'GET') {
    const empId = parseInt(req.query.employee_id, 10);
    const rows = empId
      ? await queryDb(`select * from business_leaves where employee_id=$1 order by start_date desc nulls last limit 200`, [empId])
      : await queryDb(`select * from business_leaves order by start_date desc nulls last limit 500`);
    return { leaves: rows };
  }
  const b = req.body || {};
  if (method === 'POST') {
    const days = b.days != null ? num(b.days) : (b.start_date && b.end_date ? Math.max(1, Math.round((new Date(b.end_date) - new Date(b.start_date)) / 86400000) + 1) : 1);
    const rows = await queryDb(
      `insert into business_leaves (employee_id, employee_email, type, start_date, end_date, days, status, reason)
       values ($1,$2,$3,$4,$5,$6,$7,$8) returning *`,
      [b.employee_id || null, clip(b.employee_email, 200), oneOf(b.type, LEAVE_TYPES, 'casual'), b.start_date || null, b.end_date || null, days, oneOf(b.status, LEAVE_STATUSES, 'approved'), clip(b.reason, 1000)]
    );
    return { leave: rows[0] };
  }
  if (method === 'DELETE') {
    const id = parseInt(req.query.id || b.id, 10);
    if (!id) throw httpErr(400, 'id required');
    await queryDb(`delete from business_leaves where id=$1`, [id]);
    return { ok: true };
  }
  throw httpErr(405, 'Method not allowed');
}

// Pair presence_log online→away/offline transitions into work sessions.
const sessionize = (rows) => {
  let openAt = null; const sessions = []; let totalMins = 0;
  for (const r of rows || []) {
    if (r.status === 'online') { if (!openAt) openAt = new Date(r.at); }
    else if (openAt) {
      const end = new Date(r.at); const mins = (end - openAt) / 60000;
      if (mins > 0 && mins < 16 * 60) { sessions.push({ start: openAt.toISOString(), end: end.toISOString(), mins: Math.round(mins) }); totalMins += mins; }
      openAt = null;
    }
  }
  return { sessions, totalMins: Math.round(totalMins) };
};

async function worklog(req) {
  // Detail for one employee (by email): work sessions + per-day hours + leaves.
  if (req.query.email) {
    const email = String(req.query.email);
    const days = Math.min(parseInt(req.query.days, 10) || 30, 90);
    const rows = await queryDb(`select status, at from presence_log where email=$1 and at > now() - ($2 || ' days')::interval order by at asc`, [email, String(days)]).catch(() => []);
    const { sessions, totalMins } = sessionize(rows);
    const byDay = {};
    sessions.forEach((s) => { const d = s.start.slice(0, 10); byDay[d] = (byDay[d] || 0) + s.mins; });
    const empLeaves = await queryDb(`select * from business_leaves where employee_email=$1 order by start_date desc nulls last limit 100`, [email]).catch(() => []);
    return { email, totalHours: +(totalMins / 60).toFixed(1), sessions: sessions.slice(-60).reverse(), byDay, leaves: empLeaves };
  }
  // Summary across all employees (last 7 days).
  const emps = await queryDb(`select id, name, email, title, department, status from business_employees order by name asc`).catch(() => []);
  const emails = emps.map((e) => e.email).filter(Boolean);
  let presence = [];
  if (emails.length) presence = await queryDb(`select email, status, at from presence_log where email = any($1) and at > now() - interval '7 days' order by email asc, at asc`, [emails]).catch(() => []);
  const byEmail = {};
  presence.forEach((r) => { (byEmail[r.email] = byEmail[r.email] || []).push(r); });
  const lc = Object.fromEntries((await queryDb(`select employee_email, sum(days)::float d, count(*)::int n from business_leaves group by employee_email`).catch(() => [])).map((r) => [r.employee_email, { days: r.d, n: r.n }]));
  const employeesOut = emps.map((e) => ({
    ...e,
    hoursWeek: +(sessionize(byEmail[e.email] || []).totalMins / 60).toFixed(1),
    leaveDays: lc[e.email]?.days || 0, leaveCount: lc[e.email]?.n || 0,
  }));
  return { employees: employeesOut };
}

// ── Executive command-center metrics, health score & forecast ─────────────────
const monthKey = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;

async function computeMetrics() {
  const [contactRows, dealRows, campRows, invRows, expRows, empRows] = await Promise.all([
    queryDb(`select type, stage, value, health from business_contacts`),
    queryDb(`select stage, value, probability, status, close_date, updated_at from business_deals`),
    queryDb(`select channel, status, budget, spend, leads, conversions, revenue from business_campaigns`),
    queryDb(`select amount, tax, status, due_date from business_invoices`).catch(() => []),
    queryDb(`select category, amount, status from business_expenses`).catch(() => []),
    queryDb(`select department, status, employment_type, salary from business_employees`).catch(() => []),
  ]);

  const customers = contactRows.filter((c) => c.type === 'customer');
  const leads = contactRows.filter((c) => c.type === 'lead' || c.type === 'prospect');
  const atRisk = contactRows.filter((c) => c.stage === 'at_risk' || (c.type === 'customer' && num(c.health) < 50));
  const churned = contactRows.filter((c) => c.stage === 'churned');

  const openDeals = dealRows.filter((d) => d.status === 'open');
  const wonDeals = dealRows.filter((d) => d.status === 'won');
  const lostDeals = dealRows.filter((d) => d.status === 'lost');
  const pipelineValue = openDeals.reduce((s, d) => s + num(d.value), 0);
  const weightedPipeline = openDeals.reduce((s, d) => s + num(d.value) * (num(d.probability) / 100), 0);
  const wonValue = wonDeals.reduce((s, d) => s + num(d.value), 0);
  const winRate = wonDeals.length + lostDeals.length
    ? Math.round((wonDeals.length / (wonDeals.length + lostDeals.length)) * 100) : 0;

  // Revenue trend — last 6 months of won deals by close/updated month.
  const now = new Date();
  const months = [];
  for (let i = 5; i >= 0; i--) months.push(monthKey(new Date(now.getFullYear(), now.getMonth() - i, 1)));
  const revByMonth = Object.fromEntries(months.map((m) => [m, 0]));
  wonDeals.forEach((d) => {
    const dt = d.close_date ? new Date(d.close_date) : new Date(d.updated_at);
    const k = monthKey(dt);
    if (k in revByMonth) revByMonth[k] += num(d.value);
  });
  const revenueTrend = months.map((m) => ({ month: m, revenue: Math.round(revByMonth[m]) }));

  // Simple linear forecast for next 3 months from the trend slope.
  const ys = revenueTrend.map((r) => r.revenue);
  const n = ys.length;
  const xMean = (n - 1) / 2;
  const yMean = ys.reduce((a, b) => a + b, 0) / (n || 1);
  let numr = 0, den = 0;
  ys.forEach((y, x) => { numr += (x - xMean) * (y - yMean); den += (x - xMean) ** 2; });
  const slope = den ? numr / den : 0;
  const intercept = yMean - slope * xMean;
  const forecast = [];
  for (let i = 1; i <= 3; i++) {
    const dt = new Date(now.getFullYear(), now.getMonth() + i, 1);
    forecast.push({ month: monthKey(dt), revenue: Math.max(0, Math.round(intercept + slope * (n - 1 + i))) });
  }

  // Pipeline funnel by stage.
  const funnel = DEAL_OPEN_STAGES.map((st) => ({
    stage: st,
    count: openDeals.filter((d) => d.stage === st).length,
    value: Math.round(openDeals.filter((d) => d.stage === st).reduce((s, d) => s + num(d.value), 0)),
  }));

  // Marketing roll-up.
  const totSpend = campRows.reduce((s, c) => s + num(c.spend), 0);
  const totRevenue = campRows.reduce((s, c) => s + num(c.revenue), 0);
  const totLeads = campRows.reduce((s, c) => s + num(c.leads), 0);
  const totConv = campRows.reduce((s, c) => s + num(c.conversions), 0);
  const roas = totSpend ? +(totRevenue / totSpend).toFixed(2) : 0;
  const cac = totConv ? Math.round(totSpend / totConv) : 0;
  const byChannel = CAMPAIGN_CHANNELS.map((ch) => {
    const cs = campRows.filter((c) => c.channel === ch);
    return cs.length ? { channel: ch, spend: Math.round(cs.reduce((s, c) => s + num(c.spend), 0)),
      revenue: Math.round(cs.reduce((s, c) => s + num(c.revenue), 0)),
      leads: cs.reduce((s, c) => s + num(c.leads), 0) } : null;
  }).filter(Boolean);

  const conversionRate = totLeads ? Math.round((totConv / totLeads) * 100) : 0;
  const avgCustomerValue = customers.length ? Math.round(customers.reduce((s, c) => s + num(c.value), 0) / customers.length) : 0;
  const ltv = avgCustomerValue * 3; // simple 3x annual-value heuristic
  // No customers → retention is undefined, report 0 (not a misleading 100%).
  const retention = customers.length ? Math.round(((customers.length - churned.length) / (customers.length + churned.length || 1)) * 100) : 0;

  // Composite business health score (0-100) across growth, pipeline, retention, efficiency.
  const pipelineHealth = Math.min(100, Math.round((weightedPipeline / Math.max(wonValue || 1, 1)) * 50 + winRate / 2));
  const churnRisk = customers.length ? Math.round((atRisk.length / customers.length) * 100) : 0;
  const retentionHealth = retention;
  const efficiency = Math.min(100, Math.round(roas * 20 + conversionRate));
  // An empty workspace has no signal — show 0, not a phantom score.
  const hasData = contactRows.length > 0 || dealRows.length > 0 || campRows.length > 0;
  const healthScore = !hasData ? 0 : Math.max(0, Math.min(100, Math.round(
    pipelineHealth * 0.3 + retentionHealth * 0.3 + efficiency * 0.2 + winRate * 0.2
  )));

  // Accounts (finance) roll-up.
  const today = new Date();
  const invTotal = (i) => num(i.amount) + num(i.tax);
  const collected = invRows.filter((i) => i.status === 'paid').reduce((s, i) => s + invTotal(i), 0);
  const outstanding = invRows.filter((i) => i.status === 'sent' || i.status === 'overdue').reduce((s, i) => s + invTotal(i), 0);
  const overdueAr = invRows.filter((i) => i.status === 'overdue' || (i.status === 'sent' && i.due_date && new Date(i.due_date) < today))
    .reduce((s, i) => s + invTotal(i), 0);
  const expensesPaid = expRows.filter((e) => e.status === 'paid' || e.status === 'approved').reduce((s, e) => s + num(e.amount), 0);
  const expensePending = expRows.filter((e) => e.status === 'pending').reduce((s, e) => s + num(e.amount), 0);
  const netCashflow = collected - expensesPaid;
  const expenseByCategory = EXPENSE_CATEGORIES.map((cat) => {
    const total = expRows.filter((e) => e.category === cat).reduce((s, e) => s + num(e.amount), 0);
    return total ? { category: cat, amount: Math.round(total) } : null;
  }).filter(Boolean);

  // HR roll-up.
  const activeEmps = empRows.filter((e) => e.status === 'active' || e.status === 'probation' || e.status === 'on_leave');
  const monthlyPayroll = activeEmps.reduce((s, e) => s + num(e.salary), 0) / 12;
  const headcountByDept = DEPARTMENTS.map((d) => {
    const n2 = empRows.filter((e) => e.department === d && e.status !== 'terminated').length;
    return n2 ? { department: d, count: n2 } : null;
  }).filter(Boolean);

  return {
    headline: {
      revenue: Math.round(wonValue),
      pipelineValue: Math.round(pipelineValue),
      weightedPipeline: Math.round(weightedPipeline),
      openDeals: openDeals.length,
      winRate, customers: customers.length, leads: leads.length,
      atRisk: atRisk.length, conversionRate, ltv, cac, roas, retention,
      avgCustomerValue, healthScore,
    },
    revenueTrend, forecast, funnel, byChannel,
    finance: {
      collected: Math.round(collected), outstanding: Math.round(outstanding), overdueAr: Math.round(overdueAr),
      expensesPaid: Math.round(expensesPaid), expensePending: Math.round(expensePending),
      netCashflow: Math.round(netCashflow), expenseByCategory,
    },
    hr: {
      headcount: empRows.filter((e) => e.status !== 'terminated').length,
      active: activeEmps.length, onLeave: empRows.filter((e) => e.status === 'on_leave').length,
      monthlyPayroll: Math.round(monthlyPayroll), headcountByDept,
    },
    counts: {
      contacts: contactRows.length, deals: dealRows.length, campaigns: campRows.length,
      won: wonDeals.length, lost: lostDeals.length,
      invoices: invRows.length, expenses: expRows.length, employees: empRows.length,
    },
    signals: {
      pipelineHealth, retentionHealth, efficiency, churnRisk,
    },
  };
}

// ── AI copilot — grounded on live metrics ─────────────────────────────────────
async function aiCopilot(req) {
  const question = clip((req.body || {}).question, 600) || 'Give me an executive summary of the business right now.';
  const m = await computeMetrics();
  const h = m.headline;
  const context = [
    `Won revenue (6mo): ₹${h.revenue}`, `Open pipeline: ₹${h.pipelineValue} (weighted ₹${h.weightedPipeline}, ${h.openDeals} deals)`,
    `Win rate: ${h.winRate}%`, `Customers: ${h.customers}, Leads/prospects: ${h.leads}, At-risk: ${h.atRisk}`,
    `Conversion rate: ${h.conversionRate}%, Retention: ${h.retention}%`, `LTV: ₹${h.ltv}, CAC: ₹${h.cac}, ROAS: ${h.roas}x`,
    `Business health score: ${h.healthScore}/100`,
    `Revenue trend: ${m.revenueTrend.map((r) => `${r.month}:₹${r.revenue}`).join(', ')}`,
    `3-month forecast: ${m.forecast.map((r) => `${r.month}:₹${r.revenue}`).join(', ')}`,
    `Pipeline funnel: ${m.funnel.map((f) => `${f.stage}:${f.count}(₹${f.value})`).join(', ')}`,
    `Marketing by channel: ${m.byChannel.map((c) => `${c.channel}: spend ₹${c.spend}, rev ₹${c.revenue}, ${c.leads} leads`).join('; ') || 'none'}`,
    `Finance: collected ₹${m.finance.collected}, outstanding AR ₹${m.finance.outstanding} (overdue ₹${m.finance.overdueAr}), expenses paid ₹${m.finance.expensesPaid}, net cashflow ₹${m.finance.netCashflow}`,
    `HR: ${m.hr.headcount} headcount (${m.hr.active} active, ${m.hr.onLeave} on leave), monthly payroll ₹${m.hr.monthlyPayroll}, by dept ${m.hr.headcountByDept.map((d) => `${d.department}:${d.count}`).join(', ') || 'none'}`,
  ].join('\n');

  // Greetings / trivial smalltalk get an instant, friendly reply — no AI round-trip.
  if (/^(hi|hey|hello|yo|hola|sup|good (morning|afternoon|evening)|how are you|what'?s up)\b/i.test(question.trim())) {
    return { answer: `Hi! 👋 I'm your Growth copilot. Right now: ₹${h.revenue} won (6mo), ₹${h.pipelineValue} open pipeline, ${h.customers} customers, health ${h.healthScore}/100. Ask me about revenue, pipeline, customers, campaigns, accounts or HR — e.g. "why might revenue change?" or "which customers are at risk?"`, grounded: m.headline };
  }

  const system = 'You are the AI business copilot inside the Patience AI Growth OS. Answer the operator\'s actual question directly and conversationally, grounded in the live business data provided. Cite specific numbers when relevant. Be concise (under 150 words). When the question is analytical, finish with 1-3 concrete recommended actions. Use ₹ for currency. Do not invent data not present below.';
  const prompt = `LIVE BUSINESS DATA (current snapshot):\n${context}\n\nOPERATOR QUESTION: ${question}`;

  let answer = '';
  try {
    answer = await aiComplete(prompt, { maxTokens: 320, timeoutMs: 16000, system });
  } catch {
    answer = '';
  }
  if (!answer) {
    // Deterministic, data-grounded fallback so the copilot always responds fast
    // even if the AI provider is slow or unavailable.
    answer = `Here's the live snapshot: ₹${h.revenue} won over 6 months with ₹${h.pipelineValue} in open pipeline (₹${h.weightedPipeline} weighted) across ${h.openDeals} deals. Win rate ${h.winRate}%, conversion ${h.conversionRate}%, retention ${h.retention}%, health ${h.healthScore}/100. ${h.atRisk > 0 ? `⚠ ${h.atRisk} customers at risk — prioritise outreach. ` : ''}Suggested focus: 1) Push ${m.funnel.find((f) => f.stage === 'negotiation')?.count || 0} negotiation-stage deals to close. 2) ${h.roas < 2 ? 'Reallocate spend to higher-ROAS channels.' : 'Scale your best-performing channel.'} 3) ${h.atRisk ? 'Launch a retention play for at-risk accounts.' : 'Grow top-of-funnel leads.'} (AI is busy right now — this is a live data summary.)`;
  }
  return { answer, grounded: m.headline };
}

// ── Demo seed — instantly populate a believable dataset for evaluation ────────
async function seed(me) {
  // Idempotent per-table: only populate tables that are currently empty, so a
  // partially-seeded dataset gets backfilled rather than skipped wholesale.
  const counts = await Promise.all([
    queryDb(`select count(*)::int n from business_contacts`),
    queryDb(`select count(*)::int n from business_deals`),
    queryDb(`select count(*)::int n from business_campaigns`),
  ]);
  const [hasContacts, hasDeals, hasCampaigns] = counts.map((r) => num(r[0]?.n) > 0);
  // No wholesale early-return: every block below is idempotent per-table, so an
  // install that already has CRM data still gets the Accounts/HR demo backfilled.

  // Reuse existing contacts if present, else create the demo roster.
  let ids = [];
  if (hasContacts) {
    ids = (await queryDb(`select id from business_contacts order by id asc limit 10`)).map((r) => r.id);
  }
  const cs = [
    ['Aarav Mehta', 'aarav@nimbus.io', 'Nimbus Retail', 'customer', 'active', 480000, 82],
    ['Priya Nair', 'priya@finlytics.in', 'Finlytics', 'customer', 'at_risk', 320000, 41],
    ['Rohan Gupta', 'rohan@dropwave.co', 'Dropwave', 'customer', 'active', 610000, 91],
    ['Sara Khan', 'sara@brightlearn.com', 'BrightLearn', 'prospect', 'qualified', 250000, 68],
    ['Vikram Rao', 'vikram@cargox.in', 'CargoX', 'lead', 'engaged', 0, 55],
    ['Meera Joshi', 'meera@healthsetu.in', 'HealthSetu', 'lead', 'new', 0, 50],
    ['Daniel Cruz', 'daniel@northpeak.io', 'NorthPeak', 'prospect', 'qualified', 180000, 72],
    ['Anita Desai', 'anita@quantedge.in', 'QuantEdge', 'customer', 'churned', 0, 20],
    ['Karan Singh', 'karan@looplabs.io', 'LoopLabs', 'partner', 'active', 0, 88],
    ['Neha Verma', 'neha@trekstack.com', 'TrekStack', 'lead', 'engaged', 0, 60],
  ];
  if (!hasContacts) {
    for (const [name, email, company, type, stage, value, health] of cs) {
      const r = await queryDb(
        `insert into business_contacts (name,email,company,type,stage,owner_email,value,health,score,last_touch)
         values ($1,$2,$3,$4,$5,$6,$7,$8,$9,now()) returning id`,
        [name, email, company, type, stage, me.email, value, health, Math.round(health * 0.9)]
      );
      ids.push(r[0].id);
    }
  }
  const cid = (i) => ids[i] ?? null; // tolerate fewer existing contacts

  const ds = [
    ['Nimbus — annual renewal', 0, 'negotiation', 540000, 75, 'open'],
    ['Finlytics — expansion', 1, 'proposal', 280000, 50, 'open'],
    ['Dropwave — multi-seat', 2, 'qualified', 360000, 40, 'open'],
    ['BrightLearn — new logo', 3, 'discovery', 200000, 20, 'open'],
    ['NorthPeak — pilot', 6, 'proposal', 150000, 55, 'open'],
    ['CargoX — closed pilot', 4, 'won', 120000, 100, 'won'],
    ['QuantEdge — lost renewal', 7, 'lost', 200000, 0, 'lost'],
    ['LoopLabs — partner deal', 8, 'won', 300000, 100, 'won'],
  ];
  if (!hasDeals) {
    for (const [title, ci, stage, value, prob, status] of ds) {
      await queryDb(
        `insert into business_deals (title,contact_id,pipeline,stage,value,probability,owner_email,status,close_date)
         values ($1,$2,'sales',$3,$4,$5,$6,$7, case when $7<>'open' then current_date else null end)`,
        [title, cid(ci), stage, value, prob, me.email, status]
      );
    }
  }

  const camps = [
    ['Q2 Product Launch', 'email', 'active', 150000, 92000, 420, 38, 760000],
    ['LinkedIn Thought Leadership', 'social', 'active', 80000, 61000, 210, 14, 280000],
    ['Google Search — Branded', 'paid_ads', 'active', 120000, 118000, 360, 22, 440000],
    ['Founder Webinar Series', 'webinar', 'completed', 40000, 38000, 130, 19, 380000],
    ['Referral Program', 'referral', 'active', 20000, 9000, 70, 12, 360000],
  ];
  if (!hasCampaigns) {
    for (const [name, channel, status, budget, spend, leads, conv, rev] of camps) {
      await queryDb(
        `insert into business_campaigns (name,channel,status,budget,spend,leads,conversions,revenue,start_date)
         values ($1,$2,$3,$4,$5,$6,$7,$8,current_date)`,
        [name, channel, status, budget, spend, leads, conv, rev]
      );
    }
  }

  if (!hasContacts && ids.length) {
    for (const [ci, type, subject] of [[1, 'call', 'Renewal risk call — pricing concerns'], [0, 'email', 'Sent renewal proposal'], [3, 'meeting', 'Discovery demo booked']]) {
      await queryDb(`insert into business_activities (contact_id,type,subject,actor_email) values ($1,$2,$3,$4)`,
        [cid(ci), type, subject, me.email]);
    }
    await queryDb(`insert into business_tasks (title,assignee_email,status,contact_id,due_date) values ($1,$2,'open',$3,current_date+2)`,
      ['Save the Finlytics renewal — exec call', me.email, cid(1)]);
  }

  // Accounts + HR demo data (idempotent per table).
  const [invN, expN, empN] = (await Promise.all([
    queryDb(`select count(*)::int n from business_invoices`).catch(() => [{ n: 1 }]),
    queryDb(`select count(*)::int n from business_expenses`).catch(() => [{ n: 1 }]),
    queryDb(`select count(*)::int n from business_employees`).catch(() => [{ n: 1 }]),
  ])).map((r) => num(r[0]?.n));

  if (invN === 0) {
    const invs = [
      ['INV-2041', 'Nimbus Retail', 540000, 'paid'], ['INV-2042', 'Dropwave', 300000, 'paid'],
      ['INV-2043', 'Finlytics', 280000, 'sent'], ['INV-2044', 'NorthPeak', 150000, 'overdue'],
      ['INV-2045', 'BrightLearn', 90000, 'draft'],
    ];
    for (const [number, client, amount, status] of invs) {
      await queryDb(
        `insert into business_invoices (number,client_name,amount,tax,status,issue_date,due_date,paid_date)
         values ($1,$2,$3,$4,$5,current_date-15,current_date+15, case when $5='paid' then current_date-3 else null end)`,
        [number, client, amount, Math.round(amount * 0.18), status]
      );
    }
  }
  if (expN === 0) {
    const exps = [
      ['Google Ads', 'marketing', 118000, 'paid'], ['AWS', 'infra', 84000, 'paid'],
      ['Payroll — March', 'salaries', 1450000, 'paid'], ['Figma + tools', 'software', 22000, 'approved'],
      ['Sales offsite', 'travel', 65000, 'pending'],
    ];
    for (const [vendor, category, amount, status] of exps) {
      await queryDb(`insert into business_expenses (vendor,category,amount,status,spend_date) values ($1,$2,$3,$4,current_date-7)`,
        [vendor, category, amount, status]);
    }
  }
  if (empN === 0) {
    const emps = [
      ['Aanya Sharma', 'Head of Marketing', 'Marketing', 'active', 2400000], ['Rohit Kulkarni', 'Sr. Software Engineer', 'Engineering', 'active', 2800000],
      ['Sneha Iyer', 'Customer Success Lead', 'Customer Success', 'active', 1800000], ['Arjun Patel', 'Sales Executive', 'Sales', 'active', 1200000],
      ['Divya Menon', 'HR Manager', 'HR', 'active', 1600000], ['Karthik Reddy', 'Growth Marketer', 'Marketing', 'probation', 1100000],
      ['Fatima Sheikh', 'Finance Analyst', 'Finance', 'on_leave', 1400000], ['Ishaan Bose', 'Product Designer', 'Product', 'active', 1900000],
    ];
    for (const [name, title, dept, status, salary] of emps) {
      await queryDb(
        `insert into business_employees (name,email,title,department,status,employment_type,salary,location,start_date)
         values ($1,$2,$3,$4,$5,'full_time',$6,'Bengaluru',current_date-200)`,
        [name, `${name.split(' ')[0].toLowerCase()}@patienceai.in`, title, dept, status, salary]
      );
    }
  }

  return { ok: true, seeded: {
    contacts: hasContacts ? 0 : cs.length, deals: hasDeals ? 0 : ds.length, campaigns: hasCampaigns ? 0 : camps.length,
    invoices: invN === 0 ? 5 : 0, expenses: expN === 0 ? 5 : 0, employees: empN === 0 ? 8 : 0,
  } };
}

// ── Router ────────────────────────────────────────────────────────────────────
const httpErr = (status, message) => Object.assign(new Error(message), { status });

export default async function handler(req, res) {
  const me = actorOf(req);
  if (!me) return res.status(401).json({ error: 'Not authenticated' });

  // Path segment after /api/business (e.g. metrics, ai, seed) — else resource via ?resource=.
  const seg = (req.path || req.url.split('?')[0]).replace(/^\/api\/business\/?/, '').split('/')[0];
  const resource = seg || (req.query.resource || '');

  try {
    await ensure();
    let out;
    switch (resource) {
      case '': case 'contacts': out = await contacts(req.method, req, me); break;
      case 'deals': out = await deals(req.method, req, me); break;
      case 'campaigns': out = await campaigns(req.method, req); break;
      case 'activities': out = await activities(req.method, req, me); break;
      case 'tasks': out = await tasks(req.method, req, me); break;
      case 'invoices': out = await invoices(req.method, req); break;
      case 'expenses': out = await expenses(req.method, req); break;
      case 'employees': out = await employees(req.method, req); break;
      case 'leaves': out = await leaves(req.method, req); break;
      case 'worklog': out = await worklog(req); break;
      case 'metrics': out = await computeMetrics(); break;
      case 'ai': out = await aiCopilot(req); break;
      case 'seed': out = await seed(me); break;
      default: return res.status(404).json({ error: `Unknown resource: ${resource}` });
    }
    // Activity log — every Growth create/update/delete lands in the admin audit log.
    if (['POST', 'PATCH', 'DELETE'].includes(req.method) && !['ai', 'seed', 'metrics', 'worklog'].includes(resource)) {
      logAudit('growth', me.email, `growth_${resource || 'contacts'}_${req.method.toLowerCase()}`, String((req.body || {}).id || req.query.id || (req.body || {}).name || (req.body || {}).title || '').slice(0, 120)).catch(() => {});
    }
    return res.status(200).json(out);
  } catch (e) {
    if (isMissingTableError(e.message)) return res.status(200).json({ contacts: [], deals: [], campaigns: [], activities: [], tasks: [] });
    return res.status(e.status || 500).json({ error: e.message });
  }
}
