import crypto from 'node:crypto';
import { queryDb, isMissingTableError } from './_db.js';
import { sendEmail, normalizeEmailAddress, isValidEmail } from './_email.js';
import { getCookieValue, SESSION_COOKIE_NAME, verifySessionToken } from './_security.js';

const TABLE_NAME = 'newsletter_subscriptions';

export const VALID_TOPICS = ['products', 'podcast', 'blog', 'features', 'integrations', 'legal'];

const TOPIC_LABELS = {
  products: 'Products',
  podcast: 'Podcast',
  blog: 'Blog & updates',
  features: 'Features',
  integrations: 'Integrations',
  legal: 'Terms & privacy updates'
};

const CREATE_TABLE_SQL = `create table if not exists public.${TABLE_NAME} (id bigint generated by default as identity primary key, email text not null unique, topics jsonb not null default '[]'::jsonb, confirmation_token text, confirmed_at timestamptz, unsubscribe_token text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;

let tableReady = false;
const ensureTable = async () => {
  if (tableReady) return;
  await queryDb(CREATE_TABLE_SQL);
  tableReady = true;
};

const requireAdmin = (req) => {
  const token = getCookieValue(req, SESSION_COOKIE_NAME);
  return verifySessionToken(token);
};

const sanitizeTopics = (raw) => {
  if (!Array.isArray(raw)) return [];
  return Array.from(new Set(raw.filter((t) => VALID_TOPICS.includes(t))));
};

const escapeHtml = (s = '') =>
  String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

const siteUrl = () => (process.env.SITE_URL || 'http://localhost:5173').replace(/\/$/, '');

const withUnsubscribeFooter = (html, text, unsubscribeToken) => {
  const unsubUrl = `${siteUrl()}/api/newsletter?action=unsubscribe&token=${encodeURIComponent(unsubscribeToken)}`;
  const wrappedHtml = `${html}<hr style="margin-top:32px;border:none;border-top:1px solid #eee"><p style="font-size:11px;color:#888;text-align:center;margin-top:16px">You're receiving this because you subscribed to Patience AI updates.<br><a href="${unsubUrl}" style="color:#888;text-decoration:underline">Unsubscribe</a></p>`;
  const wrappedText = `${text}\n\nUnsubscribe: ${unsubUrl}`;
  return { html: wrappedHtml, text: wrappedText };
};

const sendWelcomeEmail = async ({ email, topics, unsubscribeToken }) => {
  const list = topics.map((t) => `<li>${escapeHtml(TOPIC_LABELS[t] || t)}</li>`).join('');
  const baseHtml = `
    <div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:auto;padding:24px;color:#1a1a1a">
      <h2 style="margin:0 0 16px">You're subscribed 🎉</h2>
      <p>Thanks for joining the Patience AI newsletter. You'll get updates about:</p>
      <ul>${list || '<li>All updates</li>'}</ul>
      <p>We'll only email you when there's something genuinely new to share — no spam, no fluff.</p>
      <p style="margin:24px 0">
        <a href="${siteUrl()}" style="display:inline-block;background:#1a1a1a;color:#fff;padding:12px 22px;border-radius:9999px;text-decoration:none;font-weight:600">Visit Patience AI</a>
      </p>
    </div>`;
  const baseText = `You're subscribed to Patience AI updates: ${topics.map((t) => TOPIC_LABELS[t] || t).join(', ')}.`;
  const { html, text } = withUnsubscribeFooter(baseHtml, baseText, unsubscribeToken);
  await sendEmail({ to: email, subject: 'Welcome to Patience AI updates', html, text });
};

const subscribe = async (req, res) => {
  await ensureTable();
  const body = req.body || {};
  const email = normalizeEmailAddress(body.email || '');
  if (!isValidEmail(email)) return res.status(400).json({ error: 'Invalid email' });
  const topics = sanitizeTopics(body.topics);
  if (topics.length === 0) return res.status(400).json({ error: 'Pick at least one topic' });

  const unsubscribeToken = crypto.randomBytes(24).toString('hex');

  // Auto-confirm on signup; no email verification step required
  const rows = await queryDb(
    `INSERT INTO ${TABLE_NAME} (email, topics, confirmation_token, confirmed_at, unsubscribe_token, created_at, updated_at)
     VALUES ($1, $2::jsonb, NULL, NOW(), $3, NOW(), NOW())
     ON CONFLICT (email) DO UPDATE SET
       topics = EXCLUDED.topics,
       confirmed_at = COALESCE(${TABLE_NAME}.confirmed_at, NOW()),
       updated_at = NOW()
     RETURNING (xmax = 0) AS inserted, unsubscribe_token`,
    [email, JSON.stringify(topics), unsubscribeToken]
  );
  const row = rows[0] || { inserted: true, unsubscribe_token: unsubscribeToken };

  // Respond immediately; deliver welcome email in the background
  res.status(row.inserted ? 201 : 200).json({
    status: row.inserted ? 'subscribed' : 'updated',
    message: row.inserted
      ? "You're subscribed. We'll only email you about the topics you picked."
      : 'Your subscription preferences have been updated.'
  });

  if (row.inserted) {
    sendWelcomeEmail({ email, topics, unsubscribeToken: row.unsubscribe_token }).catch((e) => {
      console.error('[newsletter] welcome email failed:', e.message);
    });
  }
};

const confirm = async (req, res) => {
  await ensureTable();
  const token = (req.query?.token || '').toString();
  if (!token) return res.status(400).send('Missing token');
  const rows = await queryDb(
    `UPDATE ${TABLE_NAME} SET confirmed_at = NOW(), confirmation_token = NULL, updated_at = NOW()
     WHERE confirmation_token = $1 RETURNING email`,
    [token]
  );
  if (rows.length === 0) return res.status(400).send('Invalid or expired token');
  res.setHeader('Content-Type', 'text/html');
  return res.status(200).send(`<!doctype html><html><head><meta charset="utf-8"><title>Subscription confirmed</title></head>
  <body style="font-family:Inter,Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#f4f4f4">
  <div style="background:#fff;padding:40px;border-radius:24px;max-width:480px;text-align:center;box-shadow:0 10px 30px rgba(0,0,0,0.08)">
    <h1 style="margin:0 0 12px;color:#1a1a1a">You're in 🎉</h1>
    <p style="color:#666;margin:0 0 24px">Subscription confirmed for ${escapeHtml(rows[0].email)}. We'll only email you about the topics you picked.</p>
    <a href="${siteUrl()}" style="display:inline-block;background:#1a1a1a;color:#fff;padding:12px 22px;border-radius:9999px;text-decoration:none;font-weight:600">Back to Patience AI</a>
  </div></body></html>`);
};

const unsubscribe = async (req, res) => {
  await ensureTable();
  const token = (req.query?.token || '').toString();
  if (!token) return res.status(400).send('Missing token');
  const rows = await queryDb(`DELETE FROM ${TABLE_NAME} WHERE unsubscribe_token = $1 RETURNING email`, [token]);
  if (rows.length === 0) return res.status(400).send('Invalid token');
  res.setHeader('Content-Type', 'text/html');
  return res.status(200).send(`<!doctype html><html><head><meta charset="utf-8"><title>Unsubscribed</title></head>
  <body style="font-family:Inter,Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#f4f4f4">
  <div style="background:#fff;padding:40px;border-radius:24px;max-width:480px;text-align:center;box-shadow:0 10px 30px rgba(0,0,0,0.08)">
    <h1 style="margin:0 0 12px;color:#1a1a1a">You're unsubscribed</h1>
    <p style="color:#666;margin:0 0 24px">${escapeHtml(rows[0].email)} has been removed from our list.</p>
    <a href="${siteUrl()}" style="display:inline-block;background:#1a1a1a;color:#fff;padding:12px 22px;border-radius:9999px;text-decoration:none;font-weight:600">Back to Patience AI</a>
  </div></body></html>`);
};

export const broadcastTopic = async ({ topic, subject, html, text }) => {
  if (!VALID_TOPICS.includes(topic)) throw new Error('Invalid topic');
  await ensureTable();
  const rows = await queryDb(
    `SELECT email, unsubscribe_token FROM ${TABLE_NAME}
     WHERE confirmed_at IS NOT NULL AND topics @> $1::jsonb`,
    [JSON.stringify([topic])]
  );
  let sent = 0;
  const failed = [];
  for (const row of rows) {
    const { html: wrappedHtml, text: wrappedText } = withUnsubscribeFooter(html, text, row.unsubscribe_token);
    try {
      await sendEmail({ to: row.email, subject, html: wrappedHtml, text: wrappedText });
      sent += 1;
    } catch (e) {
      failed.push(row.email);
      console.error('[newsletter broadcast]', row.email, e.message);
    }
  }
  return { sent, failed };
};

const broadcast = async (req, res) => {
  if (!requireAdmin(req)) return res.status(401).json({ error: 'Unauthorized' });
  const { topic, subject, html, text } = req.body || {};
  if (!VALID_TOPICS.includes(topic)) return res.status(400).json({ error: 'Invalid topic' });
  if (!subject || !html) return res.status(400).json({ error: 'subject and html required' });
  const result = await broadcastTopic({ topic, subject, html, text: text || '' });
  return res.status(200).json(result);
};

export default async function handler(req, res) {
  const action = (req.query?.action || req.body?.action || '').toString();

  if (req.method === 'GET' && action === 'confirm') return confirm(req, res);
  if (req.method === 'GET' && action === 'unsubscribe') return unsubscribe(req, res);
  if (req.method === 'POST' && action === 'broadcast') return broadcast(req, res);
  if (req.method === 'POST') return subscribe(req, res);
  return res.status(405).json({ error: 'Method not allowed' });
}
